### ISSUE TITLE
xmonad version problem

### ISSUE THREAD

**Issue by dandelionmane** [vicfryzel/xmonad-config#25]
I was trying to trace down an issue with stalonetray, so I tried upgrading to xmonad-0.13. I installed xmonad via cabal --global, and hid my old (apt install'd) xmonad by moving it to xmonad.orig.

However, now I seem to have gotten into an inconsistent state, when I reload xmonad I get the following compile error:

xmonad.hs:82:7:
    Couldn't match type ‘xmonad-0.12:XMonad.Core.Query’
                   with ‘Query’
    NB: ‘xmonad-0.12:XMonad.Core.Query’
          is defined in ‘XMonad.Core’ in package ‘xmonad-0.12’
        ‘Query’ is defined in ‘XMonad.Core’ in package ‘xmonad-0.13’
    Expected type: Query Bool
      Actual type: xmonad-0.12:XMonad.Core.Query Bool
    In the first argument of ‘(-->)’, namely ‘isFullscreen’
    In the expression:
      isFullscreen --> (doF W.focusDown <+> doFullFloat)

I recognize this isn't really a problem with your config, but any pointers on how to fix it would still be really appreciated. :)

**Comment by dandelionmane** [comment]
Turns out I just needed to cabal install xmonad-contrib 0.13 as well.

**Comment by vicfryzel** [comment]
Hey 💃 (who knew, when you type colon then D for a :D emoji you get a dancer),

I think that the xmonad binary from cabal is referencing xmonad-contrib or other library files from your prior install, causing the incompat. To be honest, I use xmonad every day, and I'd just revert to 0.12 if I were you. I have to force myself to draw a line between debugging random stuff and getting work done, and sometimes there are so many edge cases to Linux distros & xmonad that I just abandon the pursuit and deal with the issue (thus the reason xmobar was broken since 0.12). Even as I type this, I'm on 0.12 on my home workstation, and 0.13 on my work workstation. My current HEAD I think works correctly in both.

Anyway, either update xmonad-contrib or revert. I think either should work.

**Comment by vicfryzel** [comment]
Oh great! You got it working. Nice

**Comment by dandelionmane** [comment]
:dancer: is a good emoji to reference me by, as I am a dancer :D
