### ISSUE TITLE
colorscheme and font used in the screenshot image?

### ISSUE THREAD

**Issue by sh9r** [vicfryzel/xmonad-config#31]
I was just curious about what was being used in terminal of the screenshot. I could discern vim but nothing else. Could you please let me know?

**Comment by vicfryzel** [comment]
Hi ☺️ thanks for breathing life into this project!

The color scheme is the infamous Infinite Red Black (IR Black.) I'd give you a link but I can't seem to find the original source for some reason, I think for the longest time it was in a blog post or similar. But if you search one of `irblack`, `ir_black`, or `IR Black`, you will very likely find this color scheme has already been ported to your tool.

For whatever it's worth, I've since moved on from this color scheme personally, and switched to something higher contrast. I found the pastels of IR Black to be really pretty, but in practice the difference between normal and bright wasn't easy for me to differentiate consistently when switching between desktop and laptop screens. This meant that I wasn't using half the palette most of the time, but rather increasing font weight to indicate brightness. I am currently enjoying the [Nord theme](https://nordtheme.com)!

The font is [adobe-fonts/source-code-pro](https://github.com/adobe-fonts/source-code-pro) if I remember correctly, but I might be mistaken about that.

Hope that helps!
